### ISSUE TITLE
Provider de.schlichtherle.truezip.fs.archive.tar.TarDriverService could not be instantiated

### ISSUE THREAD

**Issue by kenorb** [mojohaus/truezip#6]
I've added the following dependency to the `pom.xml` file:

    <dependency>
      <groupId>org.codehaus.mojo</groupId>
      <artifactId>truezip-maven-plugin</artifactId>
      <version>1.2</version>
    </dependency>

but when running the build, I've the following error:

> `de.schlichtherle.truezip.fs.spi.FsDriverService`: Provider `de.schlichtherle.truezip.fs.archive.tar.TarDriverService` could not be instantiated

Backtrace:

```
  at java.util.ServiceLoader.fail(ServiceLoader.java:232)
  at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
  at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
  at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
  at de.schlichtherle.truezip.fs.sl.FsDriverLocator$Boot.<clinit>(FsDriverLocator.java:77)
  at de.schlichtherle.truezip.fs.sl.FsDriverLocator.get(FsDriverLocator.java:59)
  at de.schlichtherle.truezip.file.TArchiveDetector.<init>(TArchiveDetector.java:125)
  at de.schlichtherle.truezip.file.TArchiveDetector.<init>(TArchiveDetector.java:105)
  at de.schlichtherle.truezip.file.TArchiveDetector.<clinit>(TArchiveDetector.java:80)
  at de.schlichtherle.truezip.file.TConfig.<init>(TConfig.java:170)
  at de.schlichtherle.truezip.file.TConfig.<init>(TConfig.java:90)
  at de.schlichtherle.truezip.file.TConfig$Holder.<clinit>(TConfig.java:301)
  at de.schlichtherle.truezip.file.TConfig.get(TConfig.java:110)
  at de.schlichtherle.truezip.file.TFile.<init>(TFile.java:443)
  at de.schlichtherle.truezip.file.TFile.<init>(TFile.java:409)
  at org.kreyssel.selenium.visualdiff.core.ScreenshotStore.<init>(ScreenshotStore.java:19)
  at org.kreyssel.selenium.visualdiff.core.ScreenshotManager.<init>(ScreenshotManager.java:42)
  at org.kreyssel.selenium.visualdiff.core.junit4.TakesScreenshotRule.apply(TakesScreenshotRule.java:34)
  at org.junit.runners.BlockJUnit4ClassRunner.withMethodRules(BlockJUnit4ClassRunner.java:349)
  at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:339)
  at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:256)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
  at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
  at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
  at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
Caused by: java.lang.NoClassDefFoundError: de/schlichtherle/truezip/fs/FsCharsetArchiveDriver
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at de.schlichtherle.truezip.fs.archive.tar.TarDriverService.<clinit>(TarDriverService.java:51)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
  at java.lang.Class.newInstance(Class.java:442)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
  ... 39 more
Caused by: java.lang.ClassNotFoundException: de.schlichtherle.truezip.fs.FsCharsetArchiveDriver
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 58 more
```

Any idea what's wrong and how to fix it?

**Comment by kenorb** [comment]
Ok, adding missing drivers helped I guess.

    <dependency>
      <groupId>de.schlichtherle.truezip</groupId>
      <artifactId>truezip-driver-file</artifactId>
      <version>7.7.9</version>
    </dependency>
    <dependency>
      <groupId>de.schlichtherle.truezip</groupId>
      <artifactId>truezip-kernel</artifactId>
      <version>7.7.9</version>
    </dependency>
    <dependency>
      <groupId>de.schlichtherle.truezip</groupId>
      <artifactId>truezip-driver-zip</artifactId>
      <version>7.7.9</version>
    </dependency>
